#!/bin/sh

./sitemap.pl

if [ $# == 0 ]
then
	echo "Missing commit message - exiting!"
	exit
fi

echo "Committing..."
git add .
git commit -m "$1"

echo "Committing site map..."
git add sitemap.xml
git commit -m "Updated sitemap"
